---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: egs-mar-ket-place
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: registry.deti:5000/egs-mar-ket-place/api:v1
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: egs-mar-ket-place
spec:
  ports:
  - name: cavalo
    port: 80
    targetPort: 8888
  selector:
    app: products
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: products-ingress
  namespace: egs-mar-ket-place
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http
    traefik.ingress.kubernetes.io/redirect-entry-point: http
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: maketplace.deti
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: products
            port: 
              name: cavalo
